Update DIR-882-5.0.yml

diff --git a/.github/workflows/DIR-882-5.0.yml b/.github/workflows/DIR-882-5.0.yml
--- a/.github/workflows/DIR-882-5.0.yml
+++ b/.github/workflows/DIR-882-5.0.yml
@@ -27,30 +27,27 @@ jobs:
         DEBIAN_FRONTEND: noninteractive
       run: |
         sudo apt-get update
-        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
-        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
-        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev gcc-multilib
+        sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot kmod \
+        cpio git python3-docutils gettext automake autopoint texinfo build-essential help2man pkg-config \
+        zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin 
     - name: Clone source code
       run: |
         git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u
         cd /opt/rt-n56u/toolchain-mipsel
-        mkdir -p toolchain-3.4.x
-        wget https://github.com/hanwckf/padavan-toolchain/releases/download/v1.1/mipsel-linux-uclibc.tar.xz
-        tar -xvf mipsel-linux-uclibc.tar.xz -C toolchain-3.4.x
-        mkdir -p /opt/images/
+        sh dl_toolchain.sh
     - name: Build Firmware
       env:
         TNAME: DIR-882-5.0
       run: |
         cd /opt/rt-n56u/trunk
         #wget https://raw.githubusercontent.com/chongshengB/rt-n56u/master/trunk/build_firmware_bkye
-        #sudo chmod a+x build_firmware_bkye
-        if [ ! -f configs/templates/$TNAME.config ] ; then
-        echo "configs/templates/$TNAME.config not found "
-        exit 1
-        fi
-        cp -f configs/templates/$TNAME.config .config
-        sudo ./clear_tree
+        ##sudo chmod a+x build_firmware_bkye
+        #if [ ! -f configs/templates/$TNAME.config ] ; then
+        #echo "configs/templates/$TNAME.config not found "
+        #exit 1
+        #fi
+        #cp -f configs/templates/$TNAME.config .config
+        #sudo ./clear_tree
         sudo ./build_firmware_modify $TNAME
         sudo mv -f images/*.trx /opt/images/
     - name : Upload packages
